### ISSUE TITLE
Sorry to bother you

### ISSUE THREAD

**Issue by Hail2Hydra** [courtier/NagatoroAIO#1]
First off this this is the most amazing tool ever ! super simple but extremely effective ! hardly any false Positive  

okay so my error is i can only using Bing Search engine to get any kind of results at all !

all others stop after like 4 Dorks doesn't catch any other results :/

i thought maybe error was internet on my end but i tried 3 or 4 different VPNS i have and Multiple locations i still run into the same issue.

Tried using Proxy from text and i tried all http and socks ran into the same issue

im very new to all of this so i apologize if its my fault on my ebd

**Comment by courtier** [comment]
i havent updated the code in a while so parser might be out of date for some search engines, you might be getting rate limited, idk for sure. i will look into it soon

also if you add me on telegram i can try to help u and give you some different proxies to try
@lordwolfwood or https://t.me/lordwolfwood
